vars:
  openshift: cool
  message: Where is the world going?
spring:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgresql:5432/simplecrud
    username: simplecrud
    password: simplecrud
    driver-class-name: org.postgresql.Driver
    initialization-mode: always