vars:
  openshift: cool
  message: Mais où va le monde?
spring:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/simplecrud
    username: simplecrud
    password: simplecrud
    driver-class-name: org.postgresql.Driver
    initialization-mode: always